apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: fraud_db
    user: admin
    password: password # in real project please store password in .env this is for demonstration only
    isDefault: true
    jsonData:
      sslmode: disable