version: '3.8'

services:
  pyspark:
    build: .
    container_name: pyspark_env
    ports:
      - "8888:8888"  # Jupyter Notebook
      - "4040:4040"  # Spark UI (for monitoring Spark jobs)
    volumes:
      - .:/app
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    deploy:
      resources:
        limits:
          cpus: '2'  # Limit CPU usage
          memory: 4G  # Limit memory usage