# Use an official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the producer script
COPY producer.py .
COPY Test_Process_Data.csv .

# Run the producer script
CMD ["python", "producer.py"]